homepage:
    pattern:  /
    defaults: { _controller: IOMenuBundle:Default:index }


# Commande ne cours
commande_en_cours:
    pattern:  /encours
    defaults: { _controller: IOMenuBundle:Commande:commandeEnCours }


# Carte
carte:
    pattern:  /carte
    defaults: { _controller: IOMenuBundle:Carte:index }
    
show_carte:
    pattern:  /carte/{id}
    defaults: { _controller: IOMenuBundle:Carte:showCarte }
    
show_category:
    pattern:  /carte/c/{id}
    defaults: { _controller: IOMenuBundle:Carte:showCategory }


# Dish
dish_edit:
    pattern:  /plat/{id}
    defaults: { _controller: IOMenuBundle:Dish:edit }
    
dish_update:
    pattern:  /plat/{id}/update
    defaults: { _controller: IOMenuBundle:Dish:update }


# Menu
menu_new:
    pattern:  /menu/new
    defaults: { _controller: IOMenuBundle:Menu:new }
    
menu_create:
    pattern:  /menu/create
    defaults: { _controller: IOMenuBundle:Menu:create }
