io_commande:
    resource: "@IOOrderBundle/Resources/config/routing.yml"
    prefix:   /

io_carte:
    resource: "@IOCarteBundle/Resources/config/routing.yml"
    prefix:   /

io_user:
    resource: "@IOUserBundle/Resources/config/routing.yml"
    prefix:   /

io_api:
    resource: "@IOAPIBundle/Resources/config/routing.yml"
    prefix:   /api


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"