io_order:
    resource: "@IOOrderBundle/Controller/"
    type:     annotation
    prefix:   /

io_default:
    resource: "@IODefaultBundle/Controller/"
    type:     annotation
    prefix:   /

io_restaurant:
    resource: "@IORestaurantBundle/Controller/"
    type:     annotation
    prefix:   /

io_user:
    resource: "@IOUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"