io_menu:
    resource: "@IOMenuBundle/Resources/config/routing.yml"
    prefix:   /

io_user:
    resource: "@IOUserBundle/Resources/config/routing.yml"
    prefix:   /

io_import:
    resource: "@IOImportBundle/Resources/config/routing.yml"
    prefix:   /import
  
io_api:
    resource: "@IOAPIBundle/Resources/config/routing.yml"
    prefix:   /api


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"