ioapi:
    resource: "@IOAPIBundle/Resources/config/routing.yml"
    prefix:   /

io_user:
    resource: "@IOUserBundle/Resources/config/routing.yml"
    prefix:   /

io_import:
    resource: "@IOImportBundle/Resources/config/routing.yml"
    prefix:   /import

io_menu:
    resource: "@IOMenuBundle/Resources/config/routing.yml"
    prefix:   /


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"