category_show:
    pattern:  /{id}/voir
    defaults: { _controller: "IOMenuBundle:Category:show" }

category_new:
    pattern:  /new
    defaults: { _controller: "IOMenuBundle:Category:new" }

category_create:
    pattern:  /create
    defaults: { _controller: "IOMenuBundle:Category:create" }
    requirements: { _method: post }

category_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "IOMenuBundle:Category:edit" }

category_update:
    pattern:  /{id}/update
    defaults: { _controller: "IOMenuBundle:Category:update" }
    requirements: { _method: post|put }

category_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "IOMenuBundle:Category:delete" }
    requirements: { _method: post|delete }
