homepage:
    pattern:  /
    defaults: { _controller: IOCarteBundle:Default:index }

# Carte
carte:
    pattern:  /carte
    defaults: { _controller: IOCarteBundle:Carte:index }
    
show_carte:
    pattern:  /carte/{id}
    defaults: { _controller: IOCarteBundle:Carte:showCarte }


# Category
IOCarteBundle_category:
        resource: "@IOCarteBundle/Resources/config/routing/category.yml"
        prefix:   /categorie

# Dish
IOCarteBundle_dish:
        resource: "@IOCarteBundle/Resources/config/routing/dish.yml"
        prefix:   /plat

# Menu
IOCarteBundle_menu:
        resource: "@IOCarteBundle/Resources/config/routing/menu.yml"
        prefix:   /menu

